### ISSUE TITLE
Change return type

### ISSUE THREAD

**Issue by OrbitalDweller** [OrbitalDweller/aws-change-observer#10]
Need to change return type he to be `str` instead of `LocationMarker`. Make the function return `unique_id` instead of `marker`

https://github.com/miitchellstahl/aws-change-observer/blob/091fe0671d7b928445e80e80e4c20cb7faf92e53/layers/shared_classes_layer/python/data_service.py#L37

**Comment by PCBush** [comment]
Fixed this in feature/updater-marker branch
