### ISSUE TITLE
Remove logger from DataService

### ISSUE THREAD

**Issue by OrbitalDweller** [OrbitalDweller/aws-change-observer#11]
Remove all logging from the `DataService`. Logs should be done in the Lambda. Otherwise will get very messy

https://github.com/miitchellstahl/aws-change-observer/blob/091fe0671d7b928445e80e80e4c20cb7faf92e53/layers/shared_classes_layer/python/data_service.py#L7

**Comment by PCBush** [comment]
Fixed this in feature/update-marker branch
