### ISSUE TITLE
Refactoring task

### ISSUE THREAD

**Issue by OrbitalDweller** [OrbitalDweller/aws-change-observer#15]
Here we define multiple lambda roles. They all have same definitions/permissions. We can just create one `lambda_role` and use it for all lambda

https://github.com/miitchellstahl/aws-change-observer/blob/971ec9731be167741b9d22c7b660d922c107f5ce/aws_change_observer/aws_change_observer_stack.py#L47

**Comment by PCBush** [comment]
Made a pull request for this
